#version: '3'
services:
  npm:
    image: node:16-alpine
    container_name: npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: sh -c 'npm i && npm run watch'
    networks:
      - app-network
    ports:
      - 3000:3000
      - 3001:3001
    mem_limit: 2g
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "81:81"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./deployment/local/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  #PHP Service
  php:
    container_name: php
    build:
      context: "docker/php"
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.1/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-82}:82'
    environment:
      WWWUSER: '${WWWUSER}'
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - app-network
    depends_on:
      - mysql
      - phpmyadmin
      - nginx
  mysql:
    container_name: mysql
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3307'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'app-mysql:/var/lib/mysql'
      - './docker/mysql/grant_privileges.sql:/docker-entrypoint-initdb.d/grant_privileges.sql'
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
  phpmyadmin:
    container_name: phpmyadmin
    image: 'phpmyadmin:latest'
    links:
      - mysql
    restart: always
    ports:
      - 8083:81
    networks:
      - app-network
    environment:
      - PMA_ARBITRARY=1
networks:
  app-network:
    name: "app-network"
    driver: bridge
volumes:
  app-mysql:
    name: "app-mysql"
    driver: local
