<?php

namespace Tests\Feature;

use App\User;
use Faker\Factory as Faker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Http\File;
use Illuminate\Http\UploadedFile;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;

class AwardTest extends TestCase
{
    protected $header;

    protected $data;

    public function setUp(): void
    {
        $this->header = [
            'Content-Type' => 'application/vnd.api+json',
            'Accept'       => 'application/vnd.api+json',
        ];

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetAwards()
    {
        $this->withoutExceptionHandling();
        $this->withoutMiddleware();

        $auth = User::factory()->create();
        $response = $this->actingAs($auth)->getJson(route('awards.get'), $this->header);

        $response->assertStatus(Response::HTTP_OK)->assertJsonStructure([
            'status',
            'message',
            'data'
        ]);
    }
}
