export const ru = {
	title: 'Регистрация в Jobtron.org',
	exists: 'У вас уже есть аккаунт?',
	login: 'Войти',
	canchange: 'При необходимости можно будет изменять в настройках',
	register: 'Зарегистрироваться',
	agree1: 'Создавая учетную запись, я подтверждаю, что принимаю',
	aggreement: 'Пользовательское соглашение',
	agree2: 'ознакомлен с',
	offer: 'договором оферты',
	agree3: 'и',
	terms: 'Политикой конфеденциальности',
	agree4: '.',
	phone: 'Телефон',
	name: 'Имя',
	namePlaceholder: 'Станислав',
	currency: 'Валюта',
	rub: 'Российский рубль (RUB)',
	kzt: 'Казахстанский тенге (KZT)',
	usd: 'Американский доллар (USD)',
	creating: 'Ваш кабинет создается ...',
}

export const kz = {
	title: 'Jobtron.org сайтында тіркеліңіз',
	exists: 'Есептік жазбаңыз бар ма?',
	login: 'Кіру',
	canchange: 'Қажет болса, оны параметрлерде өзгертуге болады',
	register: 'Тіркелу',
	agree1: 'Тіркелгіні жасау арқылы мен ',
	aggreement: 'Пайдаланушы келісімін ',
	agree2: 'қабылдайтынымды және ',
	offer: 'ұсыныс келісімі',
	agree3: 'және',
	terms: 'Құпиялылық саясатын оқығанымды растаймын',
	agree4: '.',
	phone: 'Телефон',
	name: 'Аты',
	namePlaceholder: 'Станислав',
	currency: 'Валюта',
	rub: 'Ресей рублі (RUB)',
	kzt: 'Қазақстан теңгесі (KZT)',
	usd: 'Америка доллары (USD)',
	creating: 'Тіркелгіңіз жасалуда ...',
}

export const en = {
	title: 'Register with Jobtron.org',
	exists: 'Already have an account?',
	login: 'Sign In',
	canchange: 'If necessary, you can change it in the settings',
	register: 'Register',
	agree1: 'By creating an account, I confirm that I accept the',
	aggreement: 'User Agreement',
	agree2: 'and have read the',
	offer: 'offer agreement',
	agree3: 'and the ',
	terms: 'Privacy Policy',
	agree4: '.',
	phone: 'Phone number',
	name: 'Name',
	namePlaceholder: 'Stanislav',
	currency: 'Currency',
	rub: 'Russian ruble (RUB)',
	kzt: 'Kazakhstani tenge (KZT)',
	usd: 'American dollar (USD)',
	creating: 'Your account is being created ...',
}
